1. In the code below, identify the object and the method.
             df.head()

The object is df and the method is head

2. Is `df.shape` an attribute or a method?

It is an attribute

3. If `df.shape` returns `(75, 8)`, explain what both numbers mean.

It means there are 75 rows and 8 columns in the dataset.

4. What type of pandas object is usually returned by `df["Data_Value"]`?

Series object

5. What type of pandas object is usually returned by `df[["County", "Data_Value"]]`?

Creates a list of column names in the series object

In [1]:
import pandas as pd

In [2]:
parks = pd.DataFrame({"Park": ["Oak", "Pine", "Maple", "Cedar"], 
                      "Area": [12, 25, 18,40],
                      "Visitors": [120, 250, 180, 310]})

In [3]:
# 6. Write the expression that selects only the `Visitors` column from the `parks` data frame.

parks["Visitors"]

0    120
1    250
2    180
3    310
Name: Visitors, dtype: int64

In [4]:
# 7. Write the expression that selects only `Park` and `Visitors` from the `parks` data frame.
parks[["Park", "Visitors"]]

    Park  Visitors
0    Oak       120
1   Pine       250
2  Maple       180
3  Cedar       310

8. What does `parks.iloc[0]` return?

It returns the first row of parks

Oak, 12, 120

9. What rows are selected by `parks.iloc[1:4]`? 

Rows 2, 3, 4. It is the indexes 1, 2, 3 but not index 4.

In [5]:
parks.iloc[1:4]

    Park  Area  Visitors
1   Pine    25       250
2  Maple    18       180
3  Cedar    40       310

In [ ]:
# 10. Write one expression that selects rows 2 through 4 by position and then keeps only `Park` and `Area`.
#parks[1:4][["Park", "Area"]]

#parks[["Park", "Area"]][1:4]
# all three of these codes work
parks.iloc[1:4][["Park", "Area"]]

    Park  Area
1   Pine    25
2  Maple    18
3  Cedar    40

In [19]:
large_area = parks[parks["Area"] > 20]

print(large_area)

    Park  Area  Visitors
1   Pine    25       250
3  Cedar    40       310